name: Data-Otter-Monitor-Active

on:
  workflow_call:
    inputs:
      applicationId:
        description: "The ID of the application"
        required: true
        type: number
      monitorId:
        description: "The ID of the monitor"
        required: true
        type: number
      active:
        description: "The active status"
        required: true
        type: boolean

jobs:
  data-otter-contact:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST request
        run: curl -X POST "http://monitoring.zgamelogic.com:8080/monitors/${{ inputs.applicationId }}/${{ inputs.monitorId }}/active/${{ inputs.active }}"