name: test

on:
  push:
jobs:
  disable-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: disable monitor
        uses: ./.github/workflows/data-otter.yml
        with:
          monitorId: 1
          active: false